package TicTacToe.models;

public enum CellState {
    FILLED,
    EMPTY,
    BLOCKED
}

// BLOCKED : JUST IN CASE IF WE ARE HAVING A DIFFERENT VERSION OF GAME
// WHERE CERTAIN CELLS ARE NOT ACCESSIBLE TO ANY PLAYER
